name: 'Docker build'
description: 'Docker Build step'
inputs:
  greet:
    description: 'Greet'
    required: false
    default: 'World'
  path_dockerfile:
    description: 'Dockerfile location'
    required: false
    default: 'Dockerfile'
  image_name:
    description: 'Image name'
    required: true
  tag_name:
    description: 'Tag name'
    required: false

runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          echo "TAG=$(date +%s)" >> $GITHUB_ENV
        else
          echo "TAG=${{ inputs.tag_name }}" >> $GITHUB_ENV
        fi
        echo "DOCKER_IMAGE_NAME=$NAME" >> $GITHUB_ENV 
        docker build . --file "$NAME" --tag academy:$(date +%s)
      shell: bash
