name: 'Docker build'
description: 'Docker Build step'
inputs:
  greet:
    description: 'Greet'
    required: false
    default: 'World'
runs:
  using: composite
  steps:
    - run: |
        echo "Hello World"
      shell: bash
