name: 'Docker push'
description: 'Docker push action'
inputs:
  dockerUsername:
    description: 'Docker username'
    required: true
  imageName:
    description: 'Docker image'
    required: true

runs:
  using: composite
  steps:
    - run: |
        docker tag ${{inputs.imageName}} ${{inputs.dockerUsername}}/${{inputs.imageName}}
        docker push $PUSH_IMAGE

      shell: bash
