name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: Build the Docker image
        uses: Saol09/academy/.github/actions/docker_build@main
        with:
          tag_name: v1
          image_name: academy
      - name: Push the Docker image
        uses: Saol09/academy/.github/actions/docker_push@main
        with:
          dockerUsername: ${{ secrets.DOCKER_USERNAME}}
          imageName: ${{env.DOCKER_IMAGE_NAME}}
      - name: List Docker images
        run: docker images
